package HW4;

//@Author : Jin Lin

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import HW4.SimulationEvent;


/**
 * Validates a simulation
 */
public class Validate {
    private static class InvalidSimulationException extends Exception {
        public InvalidSimulationException() {
        }
    }

    ;

    // Helper method for validating the simulation
    private static void check(boolean check,
                              String message) throws InvalidSimulationException {
        if (!check) {
            System.err.println("SIMULATION INVALID : " + message);
            throw new Validate.InvalidSimulationException();
        }
    }

    /**
     * Validates the given list of events is a valid simulation.
     * Returns true if the simulation is valid, false otherwise.
     *
     * @param events - a list of events generated by the simulation
     *               in the order they were generated.
     * @returns res - whether the simulation was valid or not
     */
    public static boolean validateSimulation(List<SimulationEvent> events) {
        try {
            check(events.get(0).event == SimulationEvent.EventType.SimulationStarting,
                    "Simulation didn't start with initiation event");
            check(events.get(events.size() - 1).event ==
                            SimulationEvent.EventType.SimulationEnded,
                    "Simulation didn't end with termination event");

            /* In hw3 you will write validation code for things such as:
				Should not have more eaters than specified
				Should not have more cooks than specified
				The coffee shop capacity should not be exceeded
				The capacity of each machine should not be exceeded
				Eater should not receive order until cook completes it
				Eater should not leave coffee shop until order is received
				Eater should not place more than one order
				Cook should not work on order before it is placed
			 */
            int numCustomer = 0;
            List<Integer> cookCompleteOrder = new LinkedList<Integer>();
            List<Integer> cusReceiveOrder = new LinkedList<Integer>();
            List<Customer> cusPlaceOrder = new LinkedList<Customer>();
            List<Integer> cusPlaceOrderByOrderNum = new LinkedList<Integer>();

            for (SimulationEvent e : events) {
                if (e.event == SimulationEvent.EventType.CustomerEnteredCoffeeShop) {
                    numCustomer++;
                    //System.out.println(e.event);
                }
                if (e.event == SimulationEvent.EventType.CustomerLeavingCoffeeShop) {
                    numCustomer--;
                    //System.out.println(e.event);
                }
                check(numCustomer <= Customer.getNumTable(), "The coffee shop capacity is exceeded ");

                if (e.event == SimulationEvent.EventType.CustomerPlacedOrder) {
                    check(!cusPlaceOrder.contains(e.customer), e.customer + " places more than one order");
                    cusPlaceOrder.add(e.customer);
                    cusPlaceOrderByOrderNum.add(e.orderNumber);
                }

                if (e.event == SimulationEvent.EventType.CookReceivedOrder)
                    check(cusPlaceOrderByOrderNum.contains(e.orderNumber), e.cook + " works on order " + e.orderNumber + " before it is placed");

                if (e.event == SimulationEvent.EventType.CookCompletedOrder)
                    cookCompleteOrder.add(e.orderNumber);

                if (e.event == SimulationEvent.EventType.CustomerReceivedOrder) {
                    check(cookCompleteOrder.contains(e.orderNumber), e.customer + " receives order before cook completes it");
                    cusReceiveOrder.add(e.orderNumber);
                }

                if (e.event == SimulationEvent.EventType.CustomerLeavingCoffeeShop) {
                    check(cusReceiveOrder.contains(e.customer.getOrderNum()), e.customer + " leaves before order is received");
                }
            }


            return true;
        } catch (InvalidSimulationException e) {
            return false;
        }
    }
}
